import pygame


class Events:
    TITLE_SCREEN_DEVELOPER_TIMER_EVENT: int = pygame.USEREVENT + 1
    TITLE_SCREEN_SHOW_COPYRIGHT_EVENT: int = pygame.USEREVENT + 2
    TITLE_SCREEN_TRIFORCE_START_EVENT: int = pygame.USEREVENT + 3
    TITLE_SCREEN_SHOW_TITLE_EVENT: int = pygame.USEREVENT + 4
    TITLE_SCREEN_FADE_IN_TITLE_EVENT: int = pygame.USEREVENT + 5
    TITLE_SCREEN_SHOW_SWORD_EVENT: int = pygame.USEREVENT + 6
    TITLE_SCREEN_SHOW_FLASHING_EFFECT_EVENT: int = pygame.USEREVENT + 7
    TITLE_SCREEN_SHOW_BACKGROUND_EVENT: int = pygame.USEREVENT + 8
    TITLE_SCREEN_SHOW_SHINY_EFFECT_EVENT: int = pygame.USEREVENT + 9
    TITLE_SCREEN_FADE_OUT_EVENT: int = pygame.USEREVENT + 10
    INPUT_NAME_SCREEN_START: int = pygame.USEREVENT + 11