exercise09: exercise09.o StackType.o
	g++ -std=c++14 -Wall -o exercise09 exercise09.o StackType.o

exercise09.o: exercise09.cpp StackType.h
	g++ -std=c++14 -Wall -c exercise09.cpp

StackType.o: StackType.cpp StackType.h
	g++ -std=c++14 -Wall -c StackType.cpp